### ISSUE TITLE
Differences between Exec and cgo Performance

### ISSUE THREAD

**Issue by skidder** [fawick/speedtest-resize#12]
This is a great set of benchmarks, and I really appreciate the time & effort you've made to collect this information!

My particular use-case involves resizing an image that is already in memory.  Resizing this image with cgo bindings to native libraries would likely involve no disk access.  In contrast, resizing it using a system command that is run with `exec` would involve writing the image to disk, `exec`ing the resize command of choice, and then reading the resulting image from disk.  When disk access is factored in, performing the resize with a cgo binding to a native library might outperform running commands with exec.

I'd like to see another set of benchmarks for `exec` that include the time to write & read the images from disk.

**Comment by fawick** [comment]
Sorry for the late response. I'm not sure what it is that you are asking. The benchmark times already include the time reading from and writing to disk, and there are CGO bindings for imagemagick as well as `exec.Cmd.Run` calls to `convert` process. My guess is that you are after benchmarks for the []byte -> to []byte conversion by various mean, excluding the disk I/O step? But then, what is your []byte? Is it a implementation of `draw.Image` or a an encoded JPEG? I'd chose different packages for benchmarking, depending on what the answer to that is.

To give a little more context: The reason for including the reading and writing of the files is due to the simple facts that some packages and tools only offered file-based API at the time I wrote the speedtest. At that time, my personal use-case was exclusively file-based. I'd be the first to admin that testing the performances for having a JPEG (or a `draw.Image`) as a []byte-slice and resizing that in memory might justify its own set of benchmarks. For such a use-case (at least as I understand it) I would most certainly rule out all packages that start with a file on a mass storage device.

**Comment by fawick** [comment]
It's been almost 18 months without feedback. Closing the issue.
